"""0001 initial schema

Revision ID: 72c97274bd1e
Revises: 
Create Date: 2026-05-14 22:57:04.711802
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '72c97274bd1e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan_slug', sa.String(length=50), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_proposals_per_month', sa.Integer(), nullable=False),
    sa.Column('max_storage_gb', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('branding', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('suspended_at', sa.DateTime(), nullable=True),
    sa.Column('suspension_reason', sa.String(length=500), nullable=True),
    sa.Column('default_language', sa.String(length=5), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('razao_social', sa.String(length=500), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('sap_version', sa.String(length=30), nullable=True),
    sa.Column('sap_modules', sa.JSON(), nullable=True),
    sa.Column('states', sa.JSON(), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_tenant_id'), 'companies', ['tenant_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_tenant_id'), 'knowledge_documents', ['tenant_id'], unique=False)
    op.create_index('ix_knowledge_tenant_category', 'knowledge_documents', ['tenant_id', 'category'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Constraint de unicidade: tenant_id + email'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('proposal_templates',
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('project_type', sa.String(length=30), nullable=True),
    sa.Column('default_premises', sa.JSON(), nullable=True),
    sa.Column('default_resources', sa.JSON(), nullable=True),
    sa.Column('branding', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_template_tenant_name')
    )
    op.create_index(op.f('ix_proposal_templates_tenant_id'), 'proposal_templates', ['tenant_id'], unique=False)
    op.create_table('proposals',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_type', sa.String(length=30), nullable=False),
    sa.Column('sap_version', sa.String(length=30), nullable=False),
    sa.Column('states', sa.JSON(), nullable=False),
    sa.Column('commercial_model', sa.String(length=30), nullable=False),
    sa.Column('rfp_text', sa.Text(), nullable=True),
    sa.Column('new_law', sa.Boolean(), nullable=True),
    sa.Column('hours_presale', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('lang', sa.String(length=5), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('main_proc', sa.String(length=20), nullable=True),
    sa.Column('needs_cpi', sa.Boolean(), nullable=True),
    sa.Column('total_hours', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('confidence_escopo', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('confidence_horas', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('confidence_legislacao', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('confidence_comercial', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('generation_mode', sa.String(length=20), nullable=True),
    sa.Column('agents_fired', sa.JSON(), nullable=True),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proposals_tenant_company', 'proposals', ['tenant_id', 'company_id'], unique=False)
    op.create_index('ix_proposals_tenant_created', 'proposals', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_proposals_tenant_id'), 'proposals', ['tenant_id'], unique=False)
    op.create_index('ix_proposals_tenant_status', 'proposals', ['tenant_id', 'status'], unique=False)
    op.create_table('user_company_access',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_user_company_access')
    )
    op.create_index(op.f('ix_user_company_access_tenant_id'), 'user_company_access', ['tenant_id'], unique=False)
    op.create_table('agent_executions',
    sa.Column('proposal_id', sa.String(length=36), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_exec_proposal', 'agent_executions', ['proposal_id', 'agent_name'], unique=False)
    op.create_index(op.f('ix_agent_executions_tenant_id'), 'agent_executions', ['tenant_id'], unique=False)
    op.create_table('proposal_dams',
    sa.Column('proposal_id', sa.String(length=36), nullable=False),
    sa.Column('dam_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id')
    )
    op.create_index(op.f('ix_proposal_dams_tenant_id'), 'proposal_dams', ['tenant_id'], unique=False)
    op.create_table('proposal_deliverables',
    sa.Column('proposal_id', sa.String(length=36), nullable=False),
    sa.Column('module', sa.String(length=20), nullable=False),
    sa.Column('item', sa.String(length=500), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_deliverables_tenant_id'), 'proposal_deliverables', ['tenant_id'], unique=False)
    op.create_table('proposal_legislations',
    sa.Column('proposal_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_legislations_tenant_id'), 'proposal_legislations', ['tenant_id'], unique=False)
    op.create_table('proposal_premises',
    sa.Column('proposal_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_standard', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_premises_tenant_id'), 'proposal_premises', ['tenant_id'], unique=False)
    op.create_table('proposal_resources',
    sa.Column('proposal_id', sa.String(length=36), nullable=False),
    sa.Column('frente', sa.String(length=50), nullable=False),
    sa.Column('nivel', sa.String(length=30), nullable=False),
    sa.Column('dias', sa.Integer(), nullable=False),
    sa.Column('horas', sa.Integer(), nullable=False),
    sa.Column('cost_rate', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_resources_tenant_id'), 'proposal_resources', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposal_resources_tenant_id'), table_name='proposal_resources')
    op.drop_table('proposal_resources')
    op.drop_index(op.f('ix_proposal_premises_tenant_id'), table_name='proposal_premises')
    op.drop_table('proposal_premises')
    op.drop_index(op.f('ix_proposal_legislations_tenant_id'), table_name='proposal_legislations')
    op.drop_table('proposal_legislations')
    op.drop_index(op.f('ix_proposal_deliverables_tenant_id'), table_name='proposal_deliverables')
    op.drop_table('proposal_deliverables')
    op.drop_index(op.f('ix_proposal_dams_tenant_id'), table_name='proposal_dams')
    op.drop_table('proposal_dams')
    op.drop_index(op.f('ix_agent_executions_tenant_id'), table_name='agent_executions')
    op.drop_index('ix_agent_exec_proposal', table_name='agent_executions')
    op.drop_table('agent_executions')
    op.drop_index(op.f('ix_user_company_access_tenant_id'), table_name='user_company_access')
    op.drop_table('user_company_access')
    op.drop_index('ix_proposals_tenant_status', table_name='proposals')
    op.drop_index(op.f('ix_proposals_tenant_id'), table_name='proposals')
    op.drop_index('ix_proposals_tenant_created', table_name='proposals')
    op.drop_index('ix_proposals_tenant_company', table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_proposal_templates_tenant_id'), table_name='proposal_templates')
    op.drop_table('proposal_templates')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_knowledge_tenant_category', table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_tenant_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_companies_tenant_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
